### PR TITLE
Test enhancement for namespace and assertion equal

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Add `Tests\\` namespace to load test classes automatically.
- Using the `assertSame` to make `assertEquals` values checking strict.

### CODE REVIEW

**Comment by radmen** [comment]
Hey @peter279k  thanks for the PR!

> Add Tests\\ namespace to load test classes automatically.

I don't think this is required for anything? Was there any particular case it had to be fixed?

**Comment by peter279k** [comment]
> Hey @peter279k thanks for the PR!
> 
> > Add Tests\ namespace to load test classes automatically.
> 
> I don't think this is required for anything? Was there any particular case it had to be fixed?

When running unit tests with PHPUnit, it should let classes load automatically.

It can avoid namespaces are not found when running unit tests outside this project folder.

That's why the `Test` namespace is added inside `autoload-dev` block on `composer.json` file.

**Comment by radmen** [comment]
The autoload-dev doesn't load the classes automatically. It loads them only when requested. AFAIR phpunit doesn't rely on the autoloader, instead it loads files from the directory and executes them. It doesn't need them added to the autoloader.

**Comment by peter279k** [comment]
According to the [autoload-dev reference](https://getcomposer.org/doc/04-schema.md#autoload-dev), I think it's fine to add them to the `autoload-dev` block.

The `autoload-dev` block is only for project root folder and it can avoid populating the autoloader in production.

Therefore, it is a good idea to rely on a dedicated path for your unit tests and to add it within the autoload-dev section :+1: .

**Comment by radmen** [comment]
Well, there's nothing wrong with having it :) Thanks!

**Pull request merged**
